### ISSUE TITLE
Feature: User can view a home page complete with Navbar and recipe categories 

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/cooks-cabinet#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a home page containing categories/genres of food

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to pick from a selection of recipe genres (i.e.: Italian, American, Japanese, Mexican, etc.) by clicking the category. The Navbar at the top of the application will allow for quick and easy access to other pages of the app. There will also be a search bar at the top (most likely in the navbar, although the functionality of this feature will be implemented later). 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110089434/225153729-07c83074-c595-42db-bb60-5187b4280c39.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Create a Navbar component that offers the following:
- [ ] Contains application logo
- [ ] Includes a Contact Us link
- [ ] Includes a Sign In / Sign Out button

- [ ] Create a Recipes list that includes the following:
- [ ] An icon that properly represents the food genre
- [ ] A single word describing the food genre 
- [ ] Include a link for each item of the list so the user can click to a new page with those recipes
- [ ] Use CSS to properly display the list as shown in the above wireframes.
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Remove all CSS properties that have no effect.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
