### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/cooks-cabinet#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Initialized PostgreSQL Database

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to submit POST, GET, PUT, and DELETE requests to a PostgreSQL database that retains cooking recipes.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to include necessary SQL for the creation of recipe database. It will need to include the following:
- [ ]  recipeId, name, description, steps, ingredients, createdAt, updatedAt, deleted (boolean) 
- [ ] Remove all commented out code.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
